# https://docs.docker.com/engine/install/linux-postinstall/

# https://docs.docker.com/compose/gettingstarted/

# https://devopsheaven.com/docker/docker-compose/volumes/2018/01/16/volumes-in-docker-compose.html
# Docker named volumes
# Syntax: named_volume_name:/container/path


# https://medium.com/swlh/wordpress-deployment-with-nginx-php-fpm-and-mariadb-using-docker-compose-55f59e5c1a

version: '3.3'

services:

    mariadb:

        tty: true

        container_name: mariaDB

        build: ./requirements/mariadb/

        volumes:
            - /home/shlu/data/dataBase:/var/lib/mysql

        expose:
            - 3306

        networks:
            - inter

        environment:
            USERNAME: shlu
            PASSWORD: kfhgsklf48
    
        restart: "on-failure"

    wordpress:

        container_name: WordPress

        build: ./requirements/wordpress/

        volumes: 
            - /home/shlu/data/websiteFiles:/var/www/html

        expose:
            - 3306
            - 9000

        networks:
            - inter

        environment:
            WORDPRESS_db_host: mariadb:3306

        depends_on:
            - mariadb

        restart: "on-failure"

        # stdin_open: true
        # tty: true

    nginx:

        container_name: nginx

        build: ./requirements/nginx/

        expose:
            - 9000

        ports:
            - 443:443

        networks:
            - inter

        depends_on:
            - mariadb
            - wordpress
            
        restart: "on-failure"

        # stdin_open: true
        # tty: true

networks:
    inter: