# https://docs.docker.com/engine/install/linux-postinstall/

# https://docs.docker.com/compose/gettingstarted/

# https://devopsheaven.com/docker/docker-compose/volumes/2018/01/16/volumes-in-docker-compose.html
# Docker named volumes
# Syntax: named_volume_name:/container/path


# https://medium.com/swlh/wordpress-deployment-with-nginx-php-fpm-and-mariadb-using-docker-compose-55f59e5c1a

version: '3.3'

services:

    mariadb:

        tty: true

        container_name: mariaDB

        build: ./requirements/mariadb/

        volumes:
            - db_volume:/var/lib/mysql

        expose:
            - 3306

        networks:
            - inter

        environment:
            MYSQL_USERNAME: shlu
            MYSQL_PASSWORD: kfhgsklf48
    
        restart: "on-failure"

    wordpress:

        container_name: wordpress

        build: ./requirements/wordpress/

        volumes: 
            - webfile_volume:/var/www/localhost

        expose:
            - 3306
            - 9000

        networks:
            - inter

        environment:
            WORDPRESS_db_host: mariadb:3306

        depends_on:
            - mariadb

        restart: "on-failure"

        # stdin_open: true
        # tty: true

    nginx:

        container_name: nginx

        build: ./requirements/nginx/

        volumes: 
            - webfile_volume:/var/www/localhost

        expose:
            - 9000

        ports:
            - 443:443

        networks:
            - inter

        depends_on:
            - mariadb
            - wordpress
            
        restart: "on-failure"

        # stdin_open: true
        # tty: true

volumes:
    db_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/shlu/data/dataBase/'
    webfile_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/shlu/data/websiteFiles'
    

networks:
    inter: