# https://docs.docker.com/engine/install/linux-postinstall/

# https://docs.docker.com/compose/gettingstarted/

# https://devopsheaven.com/docker/docker-compose/volumes/2018/01/16/volumes-in-docker-compose.html
# Docker named volumes
# Syntax: named_volume_name:/container/path


# https://medium.com/swlh/wordpress-deployment-with-nginx-php-fpm-and-mariadb-using-docker-compose-55f59e5c1a

version: '3.3'

services:
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #       - 8080:8080
    #     networks:
    #     - inter

    mariadb:

        container_name: mariadb

        build: ./requirements/mariadb/

        volumes:
            - db_volume:/var/lib/mysql

        expose:
            - 3306

        networks:
            - inter

        env_file: .env

        restart: "on-failure"

    wordpress:

        container_name: wordpress

        build: ./requirements/wordpress/

        volumes: 
            - webfile_volume:/var/www/wordpress

        expose:
            - 9000

        networks:
            - inter

        depends_on:
            - mariadb

        restart: "on-failure"

    nginx:

        container_name: nginx

        build: ./requirements/nginx/

        volumes: 
            - webfile_volume:/var/www/localhost

        # expose:
        #     - 9000

        ports:
            - 443:443

        networks:
            - inter

        depends_on:
            - mariadb
            - wordpress
            
        restart: "on-failure"


volumes:
    db_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/shlu/data/dataBase/'
    webfile_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/shlu/data/websiteFiles'
    

networks:
    inter: