# https://docs.docker.com/engine/install/linux-postinstall/

# https://docs.docker.com/compose/gettingstarted/

# https://devopsheaven.com/docker/docker-compose/volumes/2018/01/16/volumes-in-docker-compose.html
# Docker named volumes
# Syntax: named_volume_name:/container/path


# https://medium.com/swlh/wordpress-deployment-with-nginx-php-fpm-and-mariadb-using-docker-compose-55f59e5c1a
version: '3.3'

services:

    # mariadb:
    #     build: ./requirements/mariadb/

    #     volumes: /home/shlu/data/db/:var/lib/mysql

    #     restart: always

    # wordpress:
    #     build: ./requirements/wordpress/

    #     volumes: /home/shlu/data/html:/var/www/html

    #     depends_on: mariadb

    #     restart: always

    nginx:
        build: ./requirements/nginx/

        ports: 
            - 443
            
        restart: always