# https://docs.docker.com/engine/install/linux-postinstall/

# https://docs.docker.com/compose/gettingstarted/

# https://devopsheaven.com/docker/docker-compose/volumes/2018/01/16/volumes-in-docker-compose.html
# Docker named volumes
# Syntax: named_volume_name:/container/path


# https://medium.com/swlh/wordpress-deployment-with-nginx-php-fpm-and-mariadb-using-docker-compose-55f59e5c1a

services:

    mariadb:
        build: ./requirement/mariadb/

        ports:

        volumes: /home/shlu/data/db/:var/lib/mysql

        restart: always

    wordpress:
        build: ./wordpress/

        ports: 

        volumes: /home/shlu/data/html:/var/www/html

        restart: always

    nginx:
        build: ./requirement/nginx/

        ports:

        volumes:
            


volumes: 
