CREATE OR REPLACE USER MYSQL_USERNAME@localhost IDENTIFIED BY "MYSQL_PASSWORD";
CREATE DATABASE wordpress;
GRANT ALL PRIVILEGES ON wordpress.* TO MYSQL_USERNAME@'%' IDENTIFIED BY "MYSQL_PASSWORD";
FLUSH PRIVILEGES;